export const iconMap = {
    "01d": "meteocons:clear-day",
    "01n": "meteocons:clear-night",
    "02d": "meteocons:partly-cloudy-day",
    "02n": "meteocons:partly-cloudy-night",
    "03d": "meteocons:cloudy",
    "03n": "meteocons:cloudy",
    "04d": "meteocons:overcast",
    "04n": "meteocons:overcast",
    "09d": "meteocons:rain",
    "09n": "meteocons:rain",
    "10d": "meteocons:rain",
    "10n": "meteocons:rain",
    "11d": "meteocons:thunderstorms-day",
    "11n": "meteocons:thunderstorms-night",
    "13d": "meteocons:overcast-day-snow",
    "13n": "meteocons:overcast-night-snow",
    "50d": "meteocons:fog-day",
    "50n": "meteocons:fog-night",
}